export enum AnimalClassEnum {
    TERNERA = 1,
    TERNERO_MACHO_ENTERO = 2,
    TERNERO_MACHO_CASTRADO = 3,
    HEMBRA_DESTETADA = 4,
    MACHO_ENTERO_DESTETADO = 5,
    MACHO_CASTRADO_DESTETADO = 6,
    VAQUILLA = 7,
    VACA = 8,
    HEMBRA_ESTERILIZADA = 9,
    TORO = 10,
    NOVILLO = 11,
}
